-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")

 vim.api.nvim_set_hl(0,'Normal', {bg="none"})
 vim.api.nvim_set_hl(0,'@tag', {fg="#FFFFFF"})
 vim.api.nvim_set_hl(0,'@variable', {fg="#F72585"} )
 vim.api.nvim_set_hl(0,'@keyword', {fg="#00B4D8"} )
 vim.api.nvim_set_hl(0,'Function', {fg="#FFC8DD"})
 vim.api.nvim_set_hl(0,'@string', {fg="#FFDB00"} )
 vim.api.nvim_set_hl(0,'@boolean', {fg="#FFDB00"} )
 vim.api.nvim_set_hl(0,'@number', {fg="#FFDB00"})
 vim.api.nvim_set_hl(0,'@character', {fg="#FFAFCC"} )
 vim.api.nvim_set_hl(0,'LineNr', {fg="#FFFFFF", bg="#333333"} )
 vim.api.nvim_set_hl(0,'LineNrAbove', {fg="#CF45CD", bg="#333333"} )
 vim.api.nvim_set_hl(0,'LineNrBelow', {fg="#FFDB00", bg="#333333"} )
 vim.api.nvim_set_hl(0,'@float', { fg="#FFDB00"} )
 vim.api.nvim_set_hl(0,'Identifier', { fg="#FFC8DD"} )
 vim.api.nvim_set_hl(0,'@comment', { fg="#00FF00"} )
 vim.api.nvim_set_hl(0,'Visual', { fg="#CCCCCC", bg="#222222"} )
 vim.api.nvim_set_hl(0,'TabLineSel', { fg="#FFDB00", bg="#444444"} )
 vim.api.nvim_set_hl(0,'TabLine', { fg="#CCB900" ,bg="#222222"} )
 vim.api.nvim_set_hl(0,'TabLineFill', { fg="#000000"} )
 vim.api.nvim_set_hl(0,'CocInlayHint', { fg="#FF5555" ,bg="#000000"} )
